### ISSUE TITLE
Discord Issues

### ISSUE THREAD

**Issue by cheemskek** [dev-harsh1998/ota#16]
LineageOS 21-20241003-UNOFFICIAL-nabu. Device (Xiaomi Pad 5 inbuilt mic) mic does
n't work and when an earphone connected to the device via 3.5MM to USB C dongle system crash everything not working.

Step to produce:
1. Clear log
2. Open discord and join voice channel (without earphone connected)
3. Wait a little bit and then connect earphone
4. Discord starting to crash, I panicked and saved the logs.

After that system crash cant even reboot from power button menu had to force reboot

Attachment
[2024-10-04-07-42-57.txt](https://github.com/user-attachments/files/17258140/2024-10-04-07-42-57.txt)

**Comment by dev-harsh1998** [comment]
Thanks for the logs and information alongside the clear steps to reproduce the issues, I'll take a look into it both of the issues which you have opened have similar underlying cause thankfully, I'll try to see what can be done here!

**Comment by cheemskek** [comment]
thank you for building the ROM I really love it !

**Comment by dev-harsh1998** [comment]
please test the internal microphone again on discord, USB type c microphone has not been fixed in this release only the internal ones are taken care of, If there's no input again open the issue again with new logs :), I'll be looking into the USB type c headphones later when we do los-22. closing these now
